name: Comment on PR if Specific Directory Changes and Team Assigned

on:
  pull_request:
    types: [opened, synchronize, review_requested]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Check for changes in specific directory
        id: check_changes
        run: |
          if git diff --name-only origin/main | grep -q '^Python/'; then
            echo "changes_found=true" >> $GITHUB_ENV
          else
            echo "changes_found=false" >> $GITHUB_ENV
          fi

      - name: Check if comment already exists
        id: comment_check
        if: steps.team_check.outputs.team_assigned == 'true' && env.changes_found == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const commentExists = comments.some(comment => comment.body.includes("Changes were made in the `Python` folder"));
            core.setOutput("comment_exists", commentExists);

      - name: Comment on PR
        if: env.changes_found == 'true' && steps.team_check.outputs.team_assigned == 'true' && steps.comment_check.outputs.comment_exists == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Changes were made in the `Python` folder please check if you need to bump soft revision"
            })
