name: Reminder to bump soft revision

on:
  pull_request:
    branches:
      - dev
    paths:
      - Python/**.py
    types: [opened, synchronize, review_requested]

permissions:
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    env:
      COMMENT_EXISTS: false

    steps:
      - name: Check and update COMMENT_EXISTS
        id: comment_check
        uses: actions/github-script@v6
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const commentExists = comments.some(comment =>
              comment.body.includes("Changes were made in the extractors directories, please bump soft revision if needed")
            );
            core.exportVariable("COMMENT_EXISTS", commentExists);

      - name: Comment on PR
        if: env.COMMENT_EXISTS == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Changes were made in the extractors directories, please bump soft revision if needed"
            })
