name: Reminder to bump soft revision

on:
  pull_request:
    types: [opened, synchronize, review_requested]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    env:
      PR_BRANCH: ${{ github.head_ref }}
      MAIN_BRANCH: main
      COMMENT_EXISTS: false
      CHANGES_FOUND: false

    steps:
      - name: Check out the PR branch
        uses: actions/checkout@v4

      - name: Check for changes in specific directory
        run: |
          if git diff --name-only dev | grep -q '
          ^Python/'; then
            echo "CHANGES_FOUND=true" >> $GITHUB_ENV
          fi

      - name: Check if comment already exists
        id: comment_check
        if: env.CHANGES_FOUND == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            });
            const commentExists = comments.some(comment =>
            comment.body.includes("Changes were made in the extractors directories, please bump soft revision if needed")
            );
            core.setOutput("comment_exists", commentExists);

      - name: Update COMMENT_EXISTS environment variable
        if: env.CHANGES_FOUND == 'true'
        run: echo "COMMENT_EXISTS=$(steps.comment_check.outputs.comment_exists)" >> $GITHUB_ENV

      - name: Debug comment check
        run: echo "COMMENT_EXISTS=$COMMENT_EXISTS"

      - name: Comment on PR
        if: env.CHANGES_FOUND == 'true' && env.COMMENT_EXISTS == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Changes were made in the extractors directories, please bump soft revision if needed"
            })
